spring:
  application:
    name: pulley-test-api
  output:
    # Console 컬러 출력
    ansi:
      enabled: always
  datasource:
    url: 'jdbc:h2:mem:pulleytestdb'
    username: 'user'
    password: ''
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    # JPA DDL configuration properties
    generate-ddl: true
    # OSIV configuration property
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true
        show_sql: true
  h2:
    console:
      enabled: true
      path: '/h2-console'

logging:
  level:
    org:
      hibernate:
        sql: debug
        type: trace