spring:
  application:
    name: pulley-test-api
  output:
    # Console 컬러 출력
    ansi:
      enabled: always
  datasource:
    driver-class-name: org.h2.Driver
    url: 'jdbc:h2:mem:pulleytestdb;DB_CLOSE_DELAY=-1'
    username: 'sa'
    password: ''
  jpa:
    hibernate:
      ddl-auto: validate
    # JPA DDL configuration properties
    generate-ddl: false
    # OSIV configuration property
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true
        show_sql: true
    database: h2
  # script 파일로 데이터를 초기화하는 옵션 활성화
  sql:
    init:
      platform: h2
      mode: always
  h2:
    console:
      enabled: true
      path: '/h2-console'

logging:
  level:
    org:
      hibernate:
        sql: debug
        type: trace