drop table if exists grading cascade;
drop table if exists inclusion cascade;
drop table if exists problem cascade;
drop table if exists setting cascade;
drop table if exists users cascade;
drop table if exists workbook cascade;

create table grading (
                         status bigint,
                         grading_id bigint generated by default as identity,
                         inclusion_id bigint not null,
                         setting_id bigint not null,
                         primary key (grading_id)
);
create table inclusion (
                           inclusion_id bigint generated by default as identity,
                           problem_id bigint not null,
                           workbook_id bigint not null,
                           primary key (inclusion_id)
);
create table problem (
                         level bigint,
                         problem_id bigint generated by default as identity,
                         answer varchar(255),
                         unit_code varchar(255),
                         type varchar(255),
                         primary key (problem_id)
);
create table setting (
                         setting_id bigint generated by default as identity,
                         user_id bigint not null,
                         workbook_id bigint not null,
                         primary key (setting_id)
);
create table users (
                       users_id bigint generated by default as identity,
                       type varchar(255),
                       primary key (users_id)
);
create table workbook (
                          user_id bigint,
                          workbook_id bigint generated by default as identity,
                          name varchar(255),
                          primary key (workbook_id)
);
alter table if exists problem
    alter column problem_id restart with 1551;
alter table if exists grading
    add constraint FK7kajfxojnbbrj7rbhatkl8fvu
    foreign key (inclusion_id)
    references inclusion;
alter table if exists grading
    add constraint FKmkxoqr6ndh7an8ta2wdw2s86v
    foreign key (setting_id)
    references setting;
alter table if exists inclusion
    add constraint FKchihc9hoey1vdq9e7gvqhylp0
    foreign key (problem_id)
    references problem;
alter table if exists inclusion
    add constraint FKru4mgybxt4xwsbj4953noohjm
    foreign key (workbook_id)
    references workbook;
alter table if exists setting
    add constraint FKh6aep418tyli03h9u59bs8eiy
    foreign key (user_id)
    references users;
alter table if exists setting
    add constraint FK5co5kbh3trmnfhcplhcvb1pn8
    foreign key (workbook_id)
    references workbook;
alter table if exists workbook
    add constraint FK9ba4jwu50iytlj35ho1v950wu
    foreign key (user_id)
    references users;